import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/provider/Providers";
import { montserrat, nexaScript } from "@/public/fonts";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Pemilihan Bujang Gadis UNSRI",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo-ibgu.png",
    shortcut: "/images/logo-ibgu.png",
    apple: "/images/logo-ibgu.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${nexaScript.variable}`}>
        <Toaster richColors position="top-right" theme="light" />
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
