import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/provider/Providers";
import { montserrat, nexaScript } from "@/public/fonts";

export const metadata: Metadata = {
  title: "Pemilihan Bujang Gadis UNSRI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/favicon.png" type="image/x-icon" />
      </head>

      <body className={`${montserrat.className} ${nexaScript.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
